[package]
name = "mybank"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
cqrs-es = "0.4.2"
serde = { version = "1.0" , features = [ "derive" ] }
tokio = { version = "1", features = [ "full" ] }
